Document: touchmidi
Title: Debian touchmidi Manual
Author: <insert document author here>
Abstract: This manual describes what touchmidi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/touchmidi/touchmidi.sgml.gz

Format: postscript
Files: /usr/share/doc/touchmidi/touchmidi.ps.gz

Format: text
Files: /usr/share/doc/touchmidi/touchmidi.text.gz

Format: HTML
Index: /usr/share/doc/touchmidi/html/index.html
Files: /usr/share/doc/touchmidi/html/*.html
